### ISSUE TITLE
Permission to Blob Denied

### ISSUE THREAD

**Issue by Den5** [microsoft/azure-software-radio-hello-world#25]
Exited to see Blob Radio played... I am tyrying to go through "Using GNU Radio with Azure"

Within GRC, open the flowgraph [visualize_fm.grc](https://github.com/microsoft/azure-software-radio-hello-world/blob/main/exploring_grc/flowgraphs/visualize_fm.grc) in the exploring_grc/flowgraphs directory of this repo.

I see this error.... 

<Error>
<Code>PublicAccessNotPermitted</Code>
<Message>
Public access is not permitted on this storage account. RequestId:1997b20e-f01e-001e-1846-f71c5e000000 Time:2022-11-13T09:58:38.7654418Z
</Message>
</Error>

**Comment by 777arc** [comment]
Ah, yes we recently had to turn off the public access for security auditing reasons, I'll find a different Azure sub to host them in, and I'll be updating https://github.com/microsoft/azure-software-radio (see other issue for more details)
